spring:
  application:
    name: payment-gateway
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=1h
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

server:
  port: 8090

payment:
  gateway:
    base-url: https://pg.telpay.youcloudtech.com
    payment-page-base-url: https://pg.telpay.co.zw.youcloudtech.com/gateway-payments
    client-id: ${PAYMENT_CLIENT_ID}
    client-secret: ${PAYMENT_CLIENT_SECRET}
    merchant-name: ${MERCHANT_NAME}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
